language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
 - pip install -r test-requirements.txt
script:
 - nosetests -v -l DEBUG --logging-level=DEBUG --with-coverage --cover-package=configd
after_success:
  - codecov
